# Fastlane runs swiftlint from one directory above where the Fastfile lives
# so make sure all the paths are relative in that regard.

# Find all the available rules by running:
# swiftlint rules

disabled_rules:
  - trailing_whitespace
  - identifier_name
  - type_name

opt_in_rules:

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - src/Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
line_length:
  warning: 250
  error: 400

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 1000
  error: 1500

large_tuple:
  warning: 4
  error: 5
